-- Persist all editable identity fields and durable uploaded-file URLs.
ALTER TABLE users
ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS location VARCHAR(255),
ADD COLUMN IF NOT EXISTS company VARCHAR(255),
ADD COLUMN IF NOT EXISTS website TEXT,
ADD COLUMN IF NOT EXISTS title VARCHAR(255);

ALTER TABLE expert_profiles
ADD COLUMN IF NOT EXISTS website TEXT;

ALTER TABLE files
ADD COLUMN IF NOT EXISTS url TEXT;
