ALTER TABLE contracts
    ADD COLUMN IF NOT EXISTS client_signature JSONB,
    ADD COLUMN IF NOT EXISTS expert_signature JSONB,
    ADD COLUMN IF NOT EXISTS client_signed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS expert_signed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS locked_at TIMESTAMP WITH TIME ZONE;
